services:
  bot:
    image: ${BOT_IMAGE}
    extends:
      file: ./compose.yaml
      service: bot
    container_name: csz-bot-ephemeral
    restart: none
    command: "${BOT_ARGS}"
    environment:
      NODE_ENV: development
      DATABASE_PATH: ":memory:"
