name: Create E2E environment

on:
  workflow_call:
    inputs:
      args:
        description: 'Additional arguments'
        required: false
        type: string
        default: ""
      image:
        description: 'Docker image'
        required: true
        type: string
    secrets:
      bot-token:
        required: true
      client-id:
        required: true
      ssh-host:
        required: true
      ssh-username:
        required: true
      ssh-key:
        required: true
      ssh-port:
        required: true

jobs:
  create-e2e-environment:

    runs-on: ubuntu-latest

    concurrency: e2e
    environment:
      name: e2e

    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Update configuration
      env:
        BOT_TOKEN: ${{ secrets.bot-token }}
        CLIENT_ID: ${{ secrets.client-id }}
      run: |
        envsubst < .github/config.json > config.json

    - name: Read config.json
      id: config
      uses: juliangruber/read-file-action@v1
      with:
        path: ./config.json

    - name: Deploy CSZ Bot
      uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
      env:
        BOT_HOME_PATH: /home/csc
        EPHEMERAL_BOT_CONFIG: ${{ steps.config.outputs.content }}
        BOT_ARGS: ${{ inputs.args }}
        BOT_IMAGE: ${{ inputs.image }}
      with:
        host: ${{ secrets.ssh-host }}
        username: ${{ secrets.ssh-username }}
        key: ${{ secrets.ssh-key }}
        port: ${{ secrets.ssh-port }}
        envs: BOT_HOME_PATH,EPHEMERAL_BOT_CONFIG,BOT_ARGS,BOT_IMAGE
        script: ${{ env.BOT_HOME_PATH }}/deploy-ephemeral.sh
