name: Create E2E environment

on:
  workflow_call:
    inputs:
      args:
        description: 'Additional arguments'
        required: false
        type: string
        default: ""
      image:
        description: 'Docker image'
        required: true
        type: string
    secrets:
      bot-token:
        required: true
      client-id:
        required: true

jobs:
  create-e2e-environment:

    runs-on: ubuntu-latest

    concurrency: e2e
    environment:
      name: e2e

    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Update configuration
      env:
        BOT_TOKEN: ${{ secrets.bot-token }}
        CLIENT_ID: ${{ secrets.client-id }}
      run: |
        envsubst < .github/config.json > config.json

    - name: Start bot
      run: |
        docker run \
            --rm \
            -e NODE_ENV=development \
            -e DATABASE_PATH=:memory: \
            -v "$PWD/config.json:/app/config.json" \
            ${{ inputs.image-name }} ${{ inputs.args }}
