name: Create E2E environment

on:
  workflow_call:
    inputs:
      args:
        description: 'Additional arguments'
        required: false
        type: string
        default: ""
      image-name:
        description: 'Name of the docker image'
        required: true
        type: string
      image-artifact-name:
        description: 'Name of artifact where image tarball is located'
        required: true
        type: string
      image-artifact-filename:
        description: 'Name of tarball filename within the artifact'
        required: true
        type: string
    secrets:
      bot-token:
        required: true
      client-id:
        required: true

jobs:
  create-e2e-environment:

    runs-on: ubuntu-latest

    concurrency: e2e
    environment:
      name: e2e

    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.image-artifact-name }}
        path: /tmp

    - name: Load image
      run: |
        docker load --input /tmp/${{ inputs.image-artifact-filename }}

    - name: Update configuration
      run: |
        cp .github/config.json config.json
        sed -i 's/<BOT_TOKEN>/${{ secrets.bot-token }}/g' config.json
        sed -i 's/<CLIENT_ID>/${{ secrets.client-id }}/g' config.json

        cp .github/aoc.config.json aoc.config.json

    - name: Start bot
      run: |
        docker run \
            --rm \
            -e NODE_ENV=development \
            -e DATABASE_PATH=:memory: \
            -v "$PWD/config.json:/app/config.json" \
            -v "$PWD/aoc.config.json:/app/aoc.config.json" \
            ${{ inputs.image-name }} ${{ inputs.args }}
