name: Fix lockfile

on:
  workflow_dispatch:

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
        fetch-depth: 0

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install
    - uses: stefanzweifel/git-auto-commit-action@v5